### ISSUE TITLE
Add function to `Date` to get the week number for that date

### ISSUE THREAD

**Issue by Hejsil** [frmdstryr/zig-datetime#8]
Pretty self-explanatory, I think. The name would probably be `weekOfYear` or something

**Comment by frmdstryr** [comment]
Added in https://github.com/frmdstryr/zig-datetime/commit/c75c09a4bc5e9864fcce2ecaf09adf43bedb98db and https://github.com/frmdstryr/zig-datetime/commit/3bc36976397007d72cf4307401fb42f8fb359e1f

Please let me know if you find any issues.
